#!/bin/bash

set -eu

export TMDB_API_KEY=$(cat ~/.bashrc.d/tmdb)

command="$1"
case "${command}" in
  docker_build)
      cd ops/
      docker build -t piis-web:0.1.0 .
      exit $?
      ;;
  up)
      docker-compose -f ./docker-compose.yml -p piis up -d
      exit $?
      ;;
  test)
      docker exec piis_web_1 bash -c 'cd /usr/src/app && python manage.py test -v 2'
      exit $?
      ;;
  itest)
      # use testinfra to test commands
      docker exec piis_web_1 bash -c 'cd /usr/src/app && py.test -v test/test_commands.py'
      exit $?
      ;;
  down)
      docker-compose -f ./docker-compose.yml -p piis down
      exit $?
      ;;
  *)
      echo "Invalid command: '${command}'"
      exit 1
      ;;
esac
set +e
